/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/example/pocket-agent-proxy/pkcs11 */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "bridge.go"

#include <stdlib.h>
#include <string.h>

typedef unsigned char CK_BYTE;
typedef unsigned long CK_ULONG;
typedef unsigned long CK_RV;
typedef unsigned long CK_SESSION_HANDLE;
typedef unsigned long CK_OBJECT_HANDLE;
typedef unsigned long CK_SLOT_ID;
typedef unsigned long CK_FLAGS;
typedef unsigned long CK_USER_TYPE;
typedef void* CK_VOID_PTR;

typedef struct CK_ATTRIBUTE {
    unsigned long attrType;
    void* pValue;
    unsigned long ulValueLen;
} CK_ATTRIBUTE;

#define CKR_OK 0x00000000
#define CKR_FUNCTION_FAILED 0x00000006
#define CKR_ARGUMENTS_BAD 0x00000007
#define CKR_BUFFER_TOO_SMALL 0x00000150
#define CKR_CRYPTOKI_NOT_INITIALIZED 0x00000190

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern CK_RV GoInitialize(void);
extern CK_RV GoFinalize(void);
extern CK_RV GoOpenSession(CK_SLOT_ID slotID, CK_FLAGS flags, CK_SESSION_HANDLE* phSession);
extern CK_RV GoCloseSession(CK_SESSION_HANDLE hSession);
extern CK_RV GoLogin(CK_SESSION_HANDLE hSession, CK_USER_TYPE userType);
extern CK_RV GoLogout(CK_SESSION_HANDLE hSession);
extern CK_RV GoFindObjectsInit(CK_SESSION_HANDLE hSession, CK_ATTRIBUTE* pTemplate, CK_ULONG ulCount);
extern CK_RV GoFindObjects(CK_SESSION_HANDLE hSession, CK_OBJECT_HANDLE* phObject, CK_ULONG ulMaxObjectCount, CK_ULONG* pulObjectCount);
extern CK_RV GoFindObjectsFinal(CK_SESSION_HANDLE hSession);
extern CK_RV GoGetAttributeValue(CK_SESSION_HANDLE hSession, CK_OBJECT_HANDLE hObject, CK_ATTRIBUTE* pTemplate, CK_ULONG ulCount);
extern CK_RV GoSignInit(CK_SESSION_HANDLE hSession, CK_ULONG mechanism, CK_OBJECT_HANDLE hKey);
extern CK_RV GoSign(CK_SESSION_HANDLE hSession, CK_OBJECT_HANDLE hKey, CK_BYTE* pData, CK_ULONG ulDataLen, CK_BYTE* pSignature, CK_ULONG* pulSignatureLen);

#ifdef __cplusplus
}
#endif
