/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/example/pocket-agent-desktop/sk */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "bridge.go"

#include <stdlib.h>
#include <string.h>
#include <stdint.h>

// Struct definitions matching the sk-api.h ABI (OpenSSH 10 / version 0x000a0000).
// We define them here rather than #include "sk-api.h" to avoid a conflict
// between the const-qualified forward declarations in that header and the
// non-const declarations cgo auto-generates for //export functions.

struct sk_enroll_response {
	uint8_t  flags;
	uint8_t *public_key;
	size_t   public_key_len;
	uint8_t *key_handle;
	size_t   key_handle_len;
	uint8_t *signature;
	size_t   signature_len;
	uint8_t *attestation_cert;
	size_t   attestation_cert_len;
	uint8_t *authdata;
	size_t   authdata_len;
};

struct sk_sign_response {
	uint8_t  flags;
	uint32_t counter;
	uint8_t *sig_r;
	size_t   sig_r_len;
	uint8_t *sig_s;
	size_t   sig_s_len;
};

struct sk_resident_key {
	uint32_t  alg;
	size_t    slot;
	char     *application;
	void     *key; // struct sshkey * — opaque, never populated
	uint8_t   flags;
	uint8_t  *user_id;
	size_t    user_id_len;
};

struct sk_option {
	char    *name;
	char    *value;
	uint8_t  required;
};

#define SSH_SK_ERR_GENERAL          -1
#define SSH_SK_ERR_UNSUPPORTED      -2
#define SSH_SK_ERR_PIN_REQUIRED     -3
#define SSH_SK_ERR_DEVICE_NOT_FOUND -4

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern uint32_t sk_api_version(void);
extern int sk_enroll(uint32_t alg, uint8_t* challenge, size_t challengeLen, char* application, uint8_t flags, char* pin, struct sk_option** options, struct sk_enroll_response** enrollResponse);
extern int sk_sign(uint32_t alg, uint8_t* data, size_t datalen, char* application, uint8_t* keyHandle, size_t keyHandleLen, uint8_t flags, char* pin, struct sk_option** options, struct sk_sign_response** signResponse);
extern int sk_load_resident_keys(char* pin, struct sk_option** options, struct sk_resident_key*** rks, size_t* nrks);
extern void sk_free_enroll_response(struct sk_enroll_response* r);
extern void sk_free_sign_response(struct sk_sign_response* r);
extern void sk_free_resident_key(struct sk_resident_key* k);
extern void sk_free_resident_keys(struct sk_resident_key** rks, size_t nrks);

#ifdef __cplusplus
}
#endif
